# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
AWS_ACCESS_KEY_ID: AKIAJHBY3QOXLZUGABCQ
AWS_SECRET_ACCESS_KEY: d8//FhJ1odd5SUHN4TVnslFf8B2wt6rxl0sxxs2s
FOG_PROVIDER: AWS
MANDRILL_API_KEY: 6h1SmhSKNMG7nKS2-YlbXA
MAILCHIMP_API_KEY: ecdd95a9902a2b172e3013c66223770e-us3
HEROKU_API_KEY: 4e9e4988-89b9-40e0-b56c-2a4054b599b4
HEROKU_APP: triaged
TWILIO_ACCOUNT_SID: AC424168b9b1845c01914f4f7a07817e95
TWILIO_AUTH_TOKEN: fa59fa0d5cc4ef6cf49603c53184de2b
TWILIO_FROM_NUMBER: +1 207-618-8454
APPFIGURES_CLIENT_ID: 226810fe3902466292d7ffea38d51794
APPFIGURES_SECRET_ID: 08f864ffbd914b0d9e3ad56bd101d4d3
BITBUCKET_KEY: Lt2jmpWQnq3Rtxr7qk
BITBUCKET_SECRET: arLcyuvxaZSgVzpntSAXvEApG4wpSb9W

development:
  STRIPE_API_KEY: sk_test_RiXtxB4SVHpeixXl7OFsbafe
  STRIPE_CONNECT_CLIENT_ID: ca_2YsHEpX9cpzutHuyBY0z6MOU8N7qUV3J

  GITHUB_CLIENT_ID: 6bd3bee053ff4168911a
  GITHUB_SECRET: e698caaf6d812c81c5ddc98a1648eb2a0698450d
  GITHUB_WEBHOOK_URL: www.test.com

  GA_CLIENT_ID: 56189778933.apps.googleusercontent.com
  GA_SECRET: PQA1lyYnSiTcAd9UqFCWqZTz

  FOG_DIRECTORY: triaged-staging

staging:
  STRIPE_API_KEY: sk_test_RiXtxB4SVHpeixXl7OFsbafe
  STRIPE_CONNECT_CLIENT_ID: ca_2YsHEpX9cpzutHuyBY0z6MOU8N7qUV3J

  GITHUB_CLIENT_ID: 6bd3bee053ff4168911a
  GITHUB_SECRET: e698caaf6d812c81c5ddc98a1648eb2a0698450d
  GITHUB_WEBHOOK_URL: www.test.com

  GA_CLIENT_ID: 56189778933.apps.googleusercontent.com
  GA_SECRET: PQA1lyYnSiTcAd9UqFCWqZTz

  FOG_DIRECTORY: triage-staging
  NEW_RELIC: 252f970f9fe09634a6c1e99d82f37dca02756686

production:
  STRIPE_API_KEY: sk_live_9mnrTPayeyPXHnd8kIPjuTue
  STRIPE_CONNECT_CLIENT_ID: ca_2YsHMk5sAtkAp33y7mBpVBkGdW53UKdv
  #STRIPE_API_KEY: sk_test_RiXtxB4SVHpeixXl7OFsbafe
  #STRIPE_CONNECT_CLIENT_ID: ca_2YsHEpX9cpzutHuyBY0z6MOU8N7qUV3J

  GITHUB_CLIENT_ID: 70b17178292d17ac3e8e
  GITHUB_SECRET: 56203095aa7fdc46e25b2aec5319592226e8fa2b

  GA_CLIENT_ID: 1021571725941.apps.googleusercontent.com
  GA_SECRET: K22QsPPzygwYYoHtV15mbvHr

  FOG_DIRECTORY: triage-production
  NEW_RELIC: 0f320e1ad885d0b00878e655820ae5257120d0bf


