# config/sidekiq.yml
#
# Configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
---
:verbose: false
:concurrency: 15
:queues:
  - [often, 7]
  - [default, 5]
  - [seldom, 3]